spring:
  datasource:
    url: jdbc:mysql://lycyy.cc:3306/paySystem?characterEncoding=utf8
    username: root
    password: ukSAseeS5wID7pSx
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.office365.com
    username: cc233233233@outlook.com
    password: 2007360266nan200 #mail账号密码
    protocol: smtp
    port: 587
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.ssl.socketFactory.class: com.sun.mail.util.MailSSLSocketFactory
    properties.mail.smtp.ssl.socketFactory.fallback: false
    default-encoding: UTF-8
  redis:
    # redis库
    database: 0
    # redis 服务器地址
    host: lycyy.cc
    # redis 端口号
    port: 6379
    # redis 密码
    #password:
    # 连接超时时间（毫秒）
    timeout: 1000
    lettuce:
      pool:
        # 连接池最大链接数（负数表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（负数表示没有限制）
        max-wait: -1
        # 连接池最大空闲连接数
        max-idle: 8
        # 连接池最小空闲连接数
        min-idle: 0

